name: Run HyperBEAM Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  build-deps-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Ubuntu 22.04 image with dependencies, and HyperBEAM
        run: |
          # set defaults if not in a PR
          if [ "${GITHUB_EVENT_NAME}" != "pull_request" ]; then
            echo "REPO_URL=https://github.com/permaweb/HyperBEAM.git" >> $GITHUB_ENV
            echo "PR_BRANCH=main" >> $GITHUB_ENV
          else
            echo "REPO_URL=${{ github.event.pull_request.head.repo.clone_url }}" >> $GITHUB_ENV
            echo "PR_BRANCH=${{ github.event.pull_request.head.ref }}"       >> $GITHUB_ENV
          fi

          docker build --platform=linux/amd64 \
            --build-arg REPO_URL="$REPO_URL" \
            --build-arg PR_BRANCH="$PR_BRANCH" \
            -t hyperbeam-deps - <<'EOF'
          FROM ubuntu:22.04

          ARG REPO_URL
          ARG PR_BRANCH

          # 1) Install OS packages (including git)
          RUN apt-get update \
           && apt-get install -y --no-install-recommends \
              git \
              build-essential \
              cmake \
              pkg-config \
              ncurses-dev \
              libssl-dev \
              curl \
              ca-certificates \
           && rm -rf /var/lib/apt/lists/*

          # 2) Build & install Erlang OTP 27
          RUN git clone https://github.com/erlang/otp.git /tmp/otp \
           && cd /tmp/otp \
           && git checkout maint-27 \
           && ./configure \
           && make -j"$(nproc)" \
           && make install \
           && rm -rf /tmp/otp

          # 3) Install rebar3
          RUN git clone https://github.com/erlang/rebar3.git /tmp/rebar3 \
           && cd /tmp/rebar3 \
           && ./bootstrap \
           && mv rebar3 /usr/local/bin/ \
           && rm -rf /tmp/rebar3

          RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
            | sh -s -- -y --default-toolchain stable


          RUN mkdir -p /hyperbeam \
           && git clone --depth 1 --branch "$PR_BRANCH" "$REPO_URL" /hyperbeam/HyperBEAM

          EOF


      - name: Run Tests
        run: |
          docker run --rm hyperbeam-deps bash -lc "cd /hyperbeam/HyperBEAM && rebar3 eunit"

      - name: Notify Slack on Failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \":x: *HyperBEAM Tests Failed*\n*PR #${{ github.event.pull_request.number }}*: ${{ github.event.pull_request.title }}\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View test output>\"
          }" \"$SLACK_WEBHOOK_URL\"
